name: studymate
description: StudyMate is a premium AI-powered healthcare study companion for health science students.
publish_to: none
version: 0.1.0+1
environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: '>=3.13.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  flutter_riverpod: ^2.3.0
  firebase_core: ^2.18.0
  firebase_auth: ^4.11.0
  cloud_firestore: ^4.9.0
  firebase_storage: ^11.0.0
  google_sign_in: ^6.0.5
  flutter_signin_button: 2.0.0
  font_awesome_flutter: 10.7.0
  intl: ^0.18.1
  animations: ^2.0.5
  flutter_svg: ^2.0.0
  shared_preferences: ^2.1.1
  google_generative_ai: ^0.4.0
  camera: ^0.10.0
  image_picker: ^0.8.7
  record: ^5.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.0.15
  permission_handler: ^10.4.0
  uuid: ^3.0.7

dependency_overrides:
  font_awesome_flutter: 10.7.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
